import type { Catalog } from '../catalog';
import {
  DOMAINS,
  SCHEMA_VERSION,
  type ArchDoc,
  type ArchEdge,
  type ArchNode,
  type Domain,
} from '../schema';
import { flowTrace } from '../flows';
import { describeIssue, RULES, validate, type Lang } from '../validate';

export interface ExportFile {
  path: string;
  content: string;
}

const T = {
  en: {
    generated:
      'Generated by SysArch from architecture.json. Ids are stable: refer to components and connections by id.',
    summary: 'Summary',
    components: 'Components',
    connections: 'Connections',
    interfaces: 'Cross-domain interfaces',
    diagrams: 'Diagrams',
    boundaries: 'Trust boundaries',
    issues: 'Open issues',
    noIssues: 'None.',
    noInterfaces: 'None: the domains do not talk to each other.',
    count: (n: number, what: string) => `${n} ${what}`,
    componentsWord: 'components',
    connectionsWord: 'connections',
    issueCounts: (e: number, w: number, i: number) => `${e} errors, ${w} warnings, ${i} notes`,
    head: {
      component: ['id', 'type', 'label', 'properties', 'deploy'],
      connection: ['id', 'from', 'to', 'protocol', 'pins', 'payload'],
    },
    notes: 'Notes',
    flows: 'Flows',
    flowLine: (steps: number, ms: number, sla?: number) =>
      `${steps} steps, ${ms} ms end to end${sla === undefined ? '' : ` (target ${sla} ms)`}`,
    domain: { fullstack: 'Full stack', ai: 'AI', hardware: 'Hardware' } as Record<Domain, string>,
  },
  tr: {
    generated:
      "SysArch tarafından architecture.json'dan üretildi. Kimlikler sabittir: bileşen ve bağlantılara kimlikleriyle başvur.",
    summary: 'Özet',
    components: 'Bileşenler',
    connections: 'Bağlantılar',
    interfaces: 'Alanlar arası arayüzler',
    diagrams: 'Diyagramlar',
    boundaries: 'Güven sınırları',
    issues: 'Açık sorunlar',
    noIssues: 'Yok.',
    noInterfaces: 'Yok: alanlar birbiriyle konuşmuyor.',
    count: (n: number, what: string) => `${n} ${what}`,
    componentsWord: 'bileşen',
    connectionsWord: 'bağlantı',
    issueCounts: (e: number, w: number, i: number) => `${e} hata, ${w} uyarı, ${i} bilgi`,
    head: {
      component: ['kimlik', 'tür', 'etiket', 'özellikler', 'dağıtım'],
      connection: ['kimlik', 'kaynak', 'hedef', 'protokol', 'pinler', 'veri'],
    },
    notes: 'Notlar',
    flows: 'Akışlar',
    flowLine: (steps: number, ms: number, sla?: number) =>
      `${steps} adım, uçtan uca ${ms} ms${sla === undefined ? '' : ` (hedef ${sla} ms)`}`,
    domain: { fullstack: 'Full stack', ai: 'Yapay zeka', hardware: 'Donanım' } as Record<
      Domain,
      string
    >,
  },
} satisfies Record<Lang, unknown>;

// Deterministic output: same design, same bytes, clean diffs.
const byId = <T extends { id: string }>(a: T, b: T) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0);
const sortedNodes = (doc: ArchDoc) =>
  [...doc.nodes].sort(
    (a, b) => DOMAINS.indexOf(a.domain) - DOMAINS.indexOf(b.domain) || byId(a, b),
  );
const sortedProps = (props: ArchNode['props']) =>
  Object.keys(props)
    .sort()
    .map((k) => [k, props[k]] as const);

/** Table cells must not break the table: pipes and newlines are escaped. */
const cell = (s: string) => s.replaceAll('|', '\\|').replaceAll('\n', ' ');
const code = (s: string) => `\`${s}\``;
const row = (cells: string[]) => `| ${cells.map(cell).join(' | ')} |`;
const table = (head: string[], rows: string[][]) =>
  [row(head), row(head.map(() => '---')), ...rows.map(row)].join('\n');

const propsText = (n: ArchNode) =>
  sortedProps(n.props)
    .filter(([, v]) => v !== '')
    // Quote values that contain the separators, so "a, b" stays one value.
    .map(([k, v]) => `${k}=${typeof v === 'string' && /[,=]/.test(v) ? JSON.stringify(v) : v}`)
    .join(', ') || '—';
const pinsText = (e: ArchEdge) =>
  e.pins?.map((m) => `${m.role} ${m.sourcePin}→${m.targetPin}`).join(', ') || '—';
const payloadText = (e: ArchEdge) => {
  const p = e.payload;
  if (!p) return '—';
  const fields = p.fields.map((f) => `${f.name}: ${f.type}`).join('; ');
  return `${p.schemaName} {${fields}} ${p.sizeBytes} B × ${p.ratePerSec}/s${p.topic ? ` topic ${p.topic}` : ''}`;
};

/** Mermaid ids allow [A-Za-z0-9_]; labels escape quotes and stay on one line. */
const mid = (id: string) => `n_${id.replace(/[^A-Za-z0-9_]/g, '_')}`;
const mlabel = (s: string) => s.replaceAll('"', '#quot;').replace(/\s+/g, ' ');

function mermaid(nodes: ArchNode[], edges: ArchEdge[]) {
  const ids = new Set(nodes.map((n) => n.id));
  return [
    '```mermaid',
    'flowchart LR',
    ...nodes.map((n) => `  ${mid(n.id)}["${mlabel(n.label)}"]`),
    ...edges
      .filter((e) => ids.has(e.source) && ids.has(e.target))
      .map((e) => `  ${mid(e.source)} -->|${e.protocol}| ${mid(e.target)}`),
    '```',
  ].join('\n');
}

/** A flow as a sequence diagram, each step drawn in the direction the flow travels it. */
function sequence(
  steps: string[],
  visited: string[],
  nodes: Map<string, ArchNode>,
  edges: Map<string, ArchEdge>,
) {
  const label = (id: string) => mlabel(nodes.get(id)?.label ?? id);
  return [
    '```mermaid',
    'sequenceDiagram',
    ...[...new Set(visited)].map((id) => `  participant ${mid(id)} as ${label(id)}`),
    // A broken flow draws the steps it got through.
    ...visited.slice(1).map((to, i) => {
      const e = edges.get(steps[i]!)!;
      const what = e.payload ? `${e.protocol} ${mlabel(e.payload.schemaName)}` : e.protocol;
      return `  ${mid(visited[i]!)}->>${mid(to)}: ${what}`;
    }),
    '```',
  ].join('\n');
}

/**
 * ARCHITECTURE.md: the design as a document an AI coding tool (or a new
 * teammate) can read cold: what exists, how it connects, which pins and
 * payloads, where the domains meet, and what is still wrong.
 */
export function architectureMarkdown(
  doc: ArchDoc,
  catalog: Catalog,
  lang: Lang = doc.meta.exportLang,
): string {
  const t = T[lang];
  const nodes = sortedNodes(doc);
  const edges = [...doc.edges].sort(byId);
  const node = new Map(doc.nodes.map((n) => [n.id, n]));
  const issues = validate(doc, catalog);
  const count = (s: string) => issues.filter((i) => i.severity === s).length;
  const typeLabel = (n: ArchNode) => {
    const type = catalog.get(n.type);
    return type ? `${n.type} (${type.label})` : n.type;
  };
  const out: string[] = [`# ${doc.meta.name}`, ''];
  if (doc.meta.description) out.push(doc.meta.description, '');
  out.push(`> ${t.generated}`, '');

  out.push(`## ${t.summary}`, '');
  const perDomain = DOMAINS.map(
    (d) => `${t.domain[d]} ${nodes.filter((n) => n.domain === d).length}`,
  );
  out.push(
    `- ${t.count(nodes.length, t.componentsWord)} (${perDomain.join(', ')})`,
    `- ${t.count(edges.length, t.connectionsWord)}`,
    `- ${t.issues}: ${t.issueCounts(count('error'), count('warning'), count('info'))}`,
    '',
  );

  out.push(`## ${t.components}`, '');
  for (const d of DOMAINS) {
    const members = nodes.filter((n) => n.domain === d);
    if (!members.length) continue;
    out.push(`### ${t.domain[d]}`, '');
    out.push(
      table(
        t.head.component,
        members.map((n) => [
          code(n.id),
          typeLabel(n),
          n.label,
          propsText(n),
          n.deploy?.target ?? '—',
        ]),
      ),
      '',
    );
    for (const n of members.filter((m) => m.notes?.trim()))
      out.push(`**${t.notes} ${code(n.id)}:** ${n.notes!.trim()}`, '');
  }

  out.push(`## ${t.connections}`, '');
  out.push(
    edges.length
      ? table(
          t.head.connection,
          edges.map((e) => [
            code(e.id),
            code(e.source),
            code(e.target),
            e.protocol,
            pinsText(e),
            payloadText(e),
          ]),
        )
      : '—',
    '',
  );

  out.push(`## ${t.interfaces}`, '');
  const crossing = edges.filter((e) => node.get(e.source)?.domain !== node.get(e.target)?.domain);
  out.push(
    crossing.length
      ? crossing
          .map((e) => {
            const [a, b] = [node.get(e.source)!, node.get(e.target)!];
            return `- ${code(e.id)}: ${t.domain[a.domain]} ${code(a.id)} → ${t.domain[b.domain]} ${code(b.id)} over ${e.protocol}${e.payload ? ` (${e.payload.schemaName})` : ''}`;
          })
          .join('\n')
      : t.noInterfaces,
    '',
  );

  out.push(`## ${t.diagrams}`, '');
  for (const d of DOMAINS) {
    const members = nodes.filter((n) => n.domain === d);
    if (!members.length) continue;
    out.push(`### ${t.domain[d]}`, '', mermaid(members, edges), '');
  }

  if (doc.flows.length) {
    out.push(`## ${t.flows}`, '');
    for (const f of [...doc.flows].sort(byId)) {
      const trace = flowTrace(doc, f);
      out.push(
        `### ${f.name} ${code(f.id)}`,
        '',
        t.flowLine(f.steps.length, Math.round(trace.totalMs * 10) / 10, f.slaMs),
        '',
        sequence(f.steps, trace.nodeIds, node, new Map(doc.edges.map((e) => [e.id, e]))),
        '',
      );
    }
  }

  if (doc.boundaries.length) {
    out.push(`## ${t.boundaries}`, '');
    for (const b of [...doc.boundaries].sort(byId))
      out.push(`- ${code(b.id)} ${b.name} (${b.trust}): ${b.nodeIds.map(code).join(', ') || '—'}`);
    out.push('');
  }

  out.push(`## ${t.issues}`, '');
  out.push(
    issues.length
      ? issues
          .map((i) => {
            const { message, hint } = describeIssue(i, RULES, lang);
            return `- **${i.severity}** ${code(i.rule)}: ${message}${hint ? ` ${hint}` : ''}`;
          })
          .join('\n')
      : t.noIssues,
  );

  return `${out.join('\n').trimEnd()}\n`;
}

/**
 * architecture.json: the same design as data, trimmed of editor-only state
 * (positions, viewports) and sorted for stable diffs.
 */
export function architectureJson(doc: ArchDoc, catalog: Catalog): string {
  const issues = validate(doc, catalog);
  return `${JSON.stringify(
    {
      schemaVersion: SCHEMA_VERSION,
      name: doc.meta.name,
      description: doc.meta.description,
      components: sortedNodes(doc).map((n) => ({
        id: n.id,
        domain: n.domain,
        type: n.type,
        label: n.label,
        ...(n.parent && { parent: n.parent }),
        props: Object.fromEntries(sortedProps(n.props)),
        ...(n.deploy && { deploy: n.deploy }),
        ...(n.notes && { notes: n.notes }),
      })),
      connections: [...doc.edges].sort(byId).map((e) => ({
        id: e.id,
        from: e.source,
        to: e.target,
        protocol: e.protocol,
        ...(e.pins && { pins: e.pins }),
        ...(Object.keys(e.props).length && { props: Object.fromEntries(sortedProps(e.props)) }),
        ...(e.payload && { payload: e.payload }),
      })),
      flows: doc.flows,
      boundaries: doc.boundaries,
      issues: issues.map((i) => ({
        severity: i.severity,
        rule: i.rule,
        message: describeIssue(i, RULES, 'en').message,
        nodeIds: i.nodeIds,
        edgeIds: i.edgeIds,
      })),
    },
    null,
    2,
  )}\n`;
}

export const exportArchitecture = (doc: ArchDoc, catalog: Catalog): ExportFile[] => [
  { path: 'ARCHITECTURE.md', content: architectureMarkdown(doc, catalog) },
  { path: 'architecture.json', content: architectureJson(doc, catalog) },
];
