import { stringify } from 'yaml';
import type { Catalog } from '../catalog';
import type { ArchDoc, ArchEdge, ArchNode, Payload } from '../schema';
import { i2cBuses, normalizeI2cAddress } from '../validate';
import type { ExportFile } from './architecture';
import { bomFiles, wokwiFiles } from './hardware';
import { terraformFiles } from './terraform';

/*
 * Starting points, not finished code: each generator writes what the design
 * states unambiguously and leaves a README or comment where a person has to
 * decide. Output is sorted for stable diffs.
 */

const byId = (a: { id: string }, b: { id: string }) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0);

/** Compose service / folder / C identifier names derived from node ids. */
const slug = (id: string) => id.toLowerCase().replace(/[^a-z0-9_-]/g, '-');
// NFKD strips accents (ş→s, ğ→g, ö→o) but leaves Turkish ı alone, so map it first.
const cName = (s: string) =>
  s
    .replaceAll('ı', 'i')
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^\w]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '')
    .toUpperCase();

// ---------------------------------------------------------------- compose

/** Code the team writes: built from a service folder, not pulled as an image. */
const CUSTOM_CODE = new Set([
  'api',
  'frontend',
  'agent',
  'preprocessing',
  'evaluation',
  'training',
]);

/** Engine choice overrides the type's default image. */
const ENGINE_IMAGES: Record<string, { image: string; ports?: string[]; data?: string }> = {
  PostgreSQL: {
    image: 'postgres:17-alpine',
    ports: ['5432:5432'],
    data: '/var/lib/postgresql/data',
  },
  MySQL: { image: 'mysql:8.4', ports: ['3306:3306'], data: '/var/lib/mysql' },
  MongoDB: { image: 'mongo:8', ports: ['27017:27017'], data: '/data/db' },
  Redis: { image: 'redis:7-alpine', ports: ['6379:6379'], data: '/data' },
  Valkey: { image: 'valkey/valkey:8-alpine', ports: ['6379:6379'], data: '/data' },
  Memcached: { image: 'memcached:1.6-alpine', ports: ['11211:11211'] },
  RabbitMQ: {
    image: 'rabbitmq:4-management-alpine',
    ports: ['5672:5672', '15672:15672'],
    data: '/var/lib/rabbitmq',
  },
  Mosquitto: { image: 'eclipse-mosquitto:2', ports: ['1883:1883'], data: '/mosquitto/data' },
  NATS: { image: 'nats:2', ports: ['4222:4222'] },
  Qdrant: { image: 'qdrant/qdrant', ports: ['6333:6333'], data: '/qdrant/storage' },
};

/** Required secrets come from .env; compose refuses to start without them. */
const ENGINE_ENV: Record<string, Record<string, string>> = {
  PostgreSQL: { POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD in .env}' },
  MySQL: { MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:?set MYSQL_ROOT_PASSWORD in .env}' },
};

const inCompose = (n: ArchNode, catalog: Catalog) =>
  n.domain !== 'hardware' &&
  (n.deploy === undefined || n.deploy.target === 'docker') &&
  (CUSTOM_CODE.has(n.type) ||
    ENGINE_IMAGES[String(n.props.engine)] ||
    catalog.get(n.type)?.exportHints.dockerImage);

export function composeFiles(doc: ArchDoc, catalog: Catalog): ExportFile[] {
  const nodes = doc.nodes.filter((n) => inCompose(n, catalog)).sort(byId);
  if (!nodes.length) return [];
  const names = new Map(nodes.map((n) => [n.id, slug(n.id)]));
  const services: Record<string, Record<string, unknown>> = {};
  const volumes: Record<string, null> = {};
  const readmes: ExportFile[] = [];

  for (const n of nodes) {
    const name = names.get(n.id)!;
    const hints = catalog.get(n.type)?.exportHints ?? {};
    const engine = ENGINE_IMAGES[String(n.props.engine)];
    const service: Record<string, unknown> = {};

    if (CUSTOM_CODE.has(n.type)) {
      service.build = `./services/${name}`;
      readmes.push({ path: `services/${name}/README.md`, content: serviceReadme(doc, n) });
    } else service.image = engine?.image ?? hints.dockerImage;

    const ports = engine?.ports ?? hints.composePorts;
    if (ports?.length) service.ports = ports;
    const env = ENGINE_ENV[String(n.props.engine)];
    if (env) service.environment = env;
    if (engine?.data) {
      volumes[`${name}-data`] = null;
      service.volumes = [`${name}-data:${engine.data}`];
    }
    if (n.props.engine === 'Mosquitto')
      service.volumes = [
        ...((service.volumes as string[]) ?? []),
        './mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro',
      ];

    // A caller starts after what it calls.
    const deps = [
      ...new Set(doc.edges.filter((e) => e.source === n.id).map((e) => names.get(e.target))),
    ]
      .filter((d): d is string => !!d && d !== name)
      .sort();
    if (deps.length) service.depends_on = deps;
    services[name] = service;
  }

  const compose = {
    name: slug(doc.meta.name) || 'sysarch',
    services,
    ...(Object.keys(volumes).length && { volumes }),
  };
  return [
    {
      path: 'docker-compose.yml',
      content: `# Generated by SysArch. Services with build: need their code in ./services/<name>.\n${stringify(compose)}`,
    },
    ...readmes,
  ];
}

function serviceReadme(doc: ArchDoc, n: ArchNode) {
  const label = (id: string) => doc.nodes.find((x) => x.id === id)?.label ?? id;
  const line = (e: ArchEdge, other: string) =>
    `- ${e.protocol} ${label(other)}${e.payload ? `: ${e.payload.schemaName}` : ''}`;
  const edges = [...doc.edges].sort(byId);
  const incoming = edges.filter((e) => e.target === n.id).map((e) => line(e, e.source));
  const outgoing = edges.filter((e) => e.source === n.id).map((e) => line(e, e.target));
  return [
    `# ${n.label}`,
    '',
    `Type: ${n.type}. ${n.notes?.trim() ?? ''}`.trim(),
    '',
    '## Called by',
    '',
    ...(incoming.length ? incoming : ['- (none)']),
    '',
    '## Calls',
    '',
    ...(outgoing.length ? outgoing : ['- (none)']),
    '',
  ].join('\n');
}

// ---------------------------------------------------------------- OpenAPI

const kebab = (s: string) =>
  s
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^A-Za-z0-9]+/g, '-')
    .toLowerCase()
    .replace(/^-|-$/g, '');

/** Payload field types as JSON Schema; `X[]` becomes an array, unknown names an object. */
function fieldSchema(type: string): Record<string, unknown> {
  const t = type.trim();
  if (t.endsWith('[]')) return { type: 'array', items: fieldSchema(t.slice(0, -2)) };
  if (['string', 'number', 'integer', 'boolean'].includes(t)) return { type: t };
  if (t === 'int') return { type: 'integer' };
  if (t === 'bool') return { type: 'boolean' };
  return { type: 'object', description: t };
}

const payloadSchema = (p: Payload) => ({
  type: 'object',
  properties: Object.fromEntries(p.fields.map((f) => [f.name, fieldSchema(f.type)])),
  required: p.fields.map((f) => f.name),
});

/**
 * One OpenAPI document per component that receives HTTP payloads: each
 * payload becomes POST /<schema-name> with that body. Methods and responses
 * are a first draft for the team to refine.
 */
export function openApiFiles(doc: ArchDoc): ExportFile[] {
  const receivers = doc.nodes
    .filter((n) => doc.edges.some((e) => e.target === n.id && e.protocol === 'HTTP' && e.payload))
    .sort(byId);
  return receivers.map((n) => {
    const payloads = new Map<string, Payload>();
    for (const e of doc.edges)
      if (e.target === n.id && e.protocol === 'HTTP' && e.payload)
        payloads.set(e.payload.schemaName, e.payload);
    const names = [...payloads.keys()].sort();
    const spec = {
      openapi: '3.1.0',
      info: { title: n.label, version: '0.1.0' },
      paths: Object.fromEntries(
        names.map((s) => [
          `/${kebab(s)}`,
          {
            post: {
              operationId: s.charAt(0).toLowerCase() + s.slice(1),
              requestBody: {
                required: true,
                content: { 'application/json': { schema: { $ref: `#/components/schemas/${s}` } } },
              },
              responses: { '200': { description: 'OK' } },
            },
          },
        ]),
      ),
      components: {
        schemas: Object.fromEntries(names.map((s) => [s, payloadSchema(payloads.get(s)!)])),
      },
    };
    return { path: `openapi/${slug(n.id)}.yaml`, content: stringify(spec) };
  });
}

// ---------------------------------------------------------------- MQTT

export function mqttFiles(doc: ArchDoc): ExportFile[] {
  const edges = doc.edges.filter((e) => e.protocol === 'MQTT').sort(byId);
  if (!edges.length) return [];
  const label = (id: string) => doc.nodes.find((n) => n.id === id)?.label ?? id;

  const conf = [
    '# Generated by SysArch. Create the password file before starting:',
    '#   mosquitto_passwd -c /mosquitto/config/passwords <user>',
    'listener 1883',
    'allow_anonymous false',
    'password_file /mosquitto/config/passwords',
    'persistence true',
    'persistence_location /mosquitto/data/',
    '',
  ].join('\n');

  const topics = new Map<string, { payload?: Payload; clients: Set<string> }>();
  for (const e of edges) {
    const topic = e.payload?.topic ?? '(topic not set)';
    const entry = topics.get(topic) ?? { payload: e.payload, clients: new Set<string>() };
    entry.clients.add(label(e.source));
    topics.set(topic, entry);
  }
  const rows = [...topics]
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([topic, { payload, clients }]) => {
      const fields = payload?.fields.map((f) => `${f.name}: ${f.type}`).join(', ') ?? '—';
      const rate = payload ? `${payload.sizeBytes} B × ${payload.ratePerSec}/s` : '—';
      return `| \`${topic}\` | ${payload?.schemaName ?? '—'} | ${fields} | ${rate} | ${[...clients].sort().join(', ')} |`;
    });
  const md = [
    '# MQTT topics',
    '',
    '| topic | payload | fields | size × rate | clients |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');

  return [
    { path: 'mosquitto/mosquitto.conf', content: conf },
    { path: 'mosquitto/topics.md', content: md },
  ];
}

// ---------------------------------------------------------------- pins.h

/** GPIO8 → 8 (what Arduino and ESP-IDF take); other pin names stay symbolic. */
const pinNumber = (name: string) => /^(?:GPIO|IO|P)?(\d+)$/.exec(name)?.[1];

/**
 * One pins.h per controller: the pin map of every wired link it masters, and
 * the I2C addresses of the devices on its buses. Pins without a plain number
 * (a Jetson's PIN3) are written as comments to wire up by hand.
 */
export function pinsFiles(doc: ArchDoc): ExportFile[] {
  const nodes = new Map(doc.nodes.map((n) => [n.id, n]));
  const masters = [
    ...new Set(
      doc.edges.filter((e) => e.pins?.length && e.protocol !== 'Power').map((e) => e.source),
    ),
  ]
    .map((id) => nodes.get(id)!)
    .filter((n) => n.domain === 'hardware')
    .sort(byId);

  return masters.map((m) => {
    const lines = [
      `// Generated by SysArch for ${m.label}. Pin names follow the part's header.`,
      '#pragma once',
      '',
    ];
    // Sorted so bus numbering and device order do not depend on drawing order.
    const buses = i2cBuses(doc)
      .filter((b) => b.master === m.id)
      .sort((a, b) => (a.sda < b.sda ? -1 : 1))
      .map((b) => ({
        ...b,
        devices: [...b.devices].sort((x, y) => (x.edgeId < y.edgeId ? -1 : 1)),
      }));
    buses.forEach((bus, i) => {
      const first = doc.edges.find((e) => e.id === bus.devices[0]!.edgeId)!;
      const scl = first.pins!.find((p) => p.role === 'SCL')?.sourcePin;
      lines.push(`// I2C bus ${i}`);
      lines.push(define(`I2C${i}_SDA`, bus.sda));
      if (scl) lines.push(define(`I2C${i}_SCL`, scl));
      for (const d of bus.devices) {
        const dev = nodes.get(d.nodeId)!;
        const addr = normalizeI2cAddress(dev.props.i2cAddress);
        if (addr) lines.push(`#define ${cName(dev.label)}_I2C_ADDR ${addr}`);
      }
      lines.push('');
    });

    const onBus = new Set(buses.flatMap((b) => b.devices.map((d) => d.edgeId)));
    for (const e of doc.edges
      .filter(
        (x) => x.source === m.id && x.protocol !== 'Power' && !onBus.has(x.id) && x.pins?.length,
      )
      .sort(byId)) {
      const target = nodes.get(e.target)!;
      lines.push(`// ${e.protocol} ${target.label}`);
      for (const p of e.pins ?? [])
        lines.push(define(`${cName(target.label)}_${p.role}`, p.sourcePin));
      lines.push('');
    }
    return { path: `firmware/${slug(m.id)}/pins.h`, content: `${lines.join('\n').trimEnd()}\n` };
  });
}

function define(name: string, pin: string) {
  const n = pinNumber(pin);
  return n === undefined
    ? `// #define ${name} ${pin}  (not a plain GPIO number; map by hand)`
    : `#define ${name} ${n}  // ${pin}`;
}

/** Everything code-shaped the design implies, for the zip download. */
export const generateCode = (doc: ArchDoc, catalog: Catalog): ExportFile[] => [
  ...composeFiles(doc, catalog),
  ...openApiFiles(doc),
  ...mqttFiles(doc),
  ...pinsFiles(doc),
  ...wokwiFiles(doc, catalog),
  ...bomFiles(doc, catalog),
  ...terraformFiles(doc, catalog),
];
