import { presetOf, type Catalog } from '../catalog';
import type { ArchDoc, ArchEdge, ArchNode } from '../schema';
import type { ExportFile } from './architecture';

const byId = (a: { id: string }, b: { id: string }) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0);

// ---------------------------------------------------------------- Wokwi

/** Wire colors by pin role, the way breadboard builds are usually colored. */
const WIRE: Record<string, string> = {
  VCC: 'red',
  GND: 'black',
  SDA: 'blue',
  SCL: 'gold',
  MOSI: 'purple',
  MISO: 'violet',
  SCK: 'orange',
  CS: 'gray',
  TX: 'green',
  RX: 'cyan',
};
/** Spacing for parts the hardware tab has not placed yet. */
const GRID = 240;

interface WokwiPart {
  type: string;
  pin: (name: string) => string;
  serial?: [string, string];
}

/** The Wokwi part for a node: from its preset, else from a custom type's hint. */
function wokwiPart(n: ArchNode, catalog: Catalog): WokwiPart | undefined {
  const w = presetOf(n)?.wokwi;
  if (w) return { type: w.type, pin: (p) => w.pins?.[p] ?? p, serial: w.serial };
  const type = catalog.get(n.type)?.exportHints.wokwiType;
  return type ? { type, pin: (p) => p } : undefined;
}

/**
 * A Wokwi project for the hardware tab: diagram.json with every part Wokwi
 * can simulate, wired pin to pin along the links' pin maps and placed as on
 * the hardware tab, plus wokwi.toml for the VS Code extension and a README
 * naming what the simulation leaves out. Nothing when no part has a Wokwi
 * counterpart.
 */
export function wokwiFiles(doc: ArchDoc, catalog: Catalog): ExportFile[] {
  const parts = new Map<string, WokwiPart>();
  const missing: ArchNode[] = [];
  for (const n of doc.nodes.filter((x) => x.domain === 'hardware').sort(byId)) {
    const part = wokwiPart(n, catalog);
    if (part) parts.set(n.id, part);
    else missing.push(n);
  }
  if (!parts.size) return [];

  const at = doc.views.find((v) => v.id === 'hardware')?.positions ?? {};
  const connections: [string, string, string, string[]][] = [];
  for (const [id, p] of parts)
    if (p.serial)
      connections.push(
        [`${id}:${p.serial[0]}`, '$serialMonitor:RX', '', []],
        [`${id}:${p.serial[1]}`, '$serialMonitor:TX', '', []],
      );
  const unwired: ArchEdge[] = [];
  for (const e of [...doc.edges].sort(byId)) {
    const s = parts.get(e.source);
    const t = parts.get(e.target);
    if (!s || !t) continue;
    if (!e.pins?.length) unwired.push(e);
    for (const m of e.pins ?? [])
      connections.push([
        `${e.source}:${s.pin(m.sourcePin)}`,
        `${e.target}:${t.pin(m.targetPin)}`,
        WIRE[m.role] ?? 'green',
        [],
      ]);
  }

  const diagram = {
    version: 1,
    author: 'SysArch',
    editor: 'wokwi',
    parts: [...parts].map(([id, p], i) => ({
      type: p.type,
      id,
      top: at[id]?.y ?? Math.floor(i / 4) * GRID,
      left: at[id]?.x ?? (i % 4) * GRID,
      attrs: {},
    })),
    connections,
  };

  const labels = new Map(doc.nodes.map((n) => [n.id, n.label]));
  const readme = [
    '# Wokwi simulation',
    '',
    `Generated by SysArch from the hardware tab of "${doc.meta.name}".`,
    '',
    '- wokwi.com: start a project for the board, then replace its `diagram.json` with this one.',
    '- VS Code: install the Wokwi extension, build the firmware and point `wokwi.toml` at it.',
    '',
  ];
  if (missing.length)
    readme.push(
      '## Not in the simulation',
      '',
      'No Wokwi part; wire these by hand or swap in the nearest part Wokwi has.',
      '',
      ...missing.map((n) => `- ${n.label} (\`${n.id}\`)`),
      '',
    );
  if (unwired.length)
    readme.push(
      '## Not wired',
      '',
      'These links have no pin map in SysArch, so the diagram has no wires for them.',
      '',
      ...unwired.map(
        (e) => `- ${labels.get(e.source)} → ${labels.get(e.target)} (${e.protocol}, \`${e.id}\`)`,
      ),
      '',
    );

  return [
    { path: 'wokwi/diagram.json', content: `${JSON.stringify(diagram, null, 2)}\n` },
    {
      path: 'wokwi/wokwi.toml',
      content: [
        '# Wokwi for VS Code reads this file. Point both paths at your firmware build.',
        '[wokwi]',
        'version = 1',
        'firmware = "build/firmware.bin"',
        'elf = "build/firmware.elf"',
        '',
      ].join('\n'),
    },
    { path: 'wokwi/README.md', content: `${readme.join('\n').trimEnd()}\n` },
  ];
}

// ---------------------------------------------------------------- BOM

const round2 = (x: number) => Math.round(x * 100) / 100;

/** One CSV cell. Text starting with = + - @ is defused so spreadsheets don't run it. */
function cell(v: string | number | undefined) {
  if (v === undefined) return '';
  let s = String(v);
  if (typeof v === 'string' && /^[=+\-@\t\r]/.test(s)) s = `'${s}`;
  return /[",\n\r]/.test(s) ? `"${s.replaceAll('"', '""')}"` : s;
}

/**
 * Bill of materials for the hardware tab: every part its type prices as
 * BOM, grouped by real part and unit price, with quantities and totals.
 * Prices are the parts' own `priceUsd`, editable per node.
 */
export function bomFiles(doc: ArchDoc, catalog: Catalog): ExportFile[] {
  const rows = new Map<
    string,
    { part: string; type: string; unit: number | undefined; used: string[] }
  >();
  for (const n of [...doc.nodes].sort(byId)) {
    if (n.domain !== 'hardware' || catalog.get(n.type)?.exportHints.pricingKey !== 'bom') continue;
    const part = presetOf(n)?.label ?? n.label;
    const unit = typeof n.props.priceUsd === 'number' ? n.props.priceUsd : undefined;
    const key = JSON.stringify([part, n.type, unit]);
    const row = rows.get(key) ?? { part, type: n.type, unit, used: [] };
    row.used.push(n.label);
    rows.set(key, row);
  }
  if (!rows.size) return [];

  const sorted = [...rows.values()].sort((a, b) => a.part.localeCompare(b.part, 'en'));
  const lines = [['Part', 'Type', 'Quantity', 'Unit price (USD)', 'Line total (USD)', 'Used as']];
  let quantity = 0;
  let total = 0;
  let unpriced = 0;
  for (const r of sorted) {
    const q = r.used.length;
    quantity += q;
    if (r.unit === undefined) unpriced += q;
    else total += r.unit * q;
    lines.push([
      cell(r.part),
      cell(r.type),
      cell(q),
      cell(r.unit),
      cell(r.unit === undefined ? undefined : round2(r.unit * q)),
      cell(r.used.join('; ')),
    ]);
  }
  lines.push([
    'Total',
    '',
    cell(quantity),
    '',
    cell(round2(total)),
    unpriced ? cell(`${unpriced} part(s) without a price`) : '',
  ]);
  return [{ path: 'bom.csv', content: `${lines.map((l) => l.join(',')).join('\n')}\n` }];
}
