import type { Catalog } from '../catalog';
import type { ArchDoc, ArchNode } from '../schema';
import type { ExportFile } from './architecture';

/*
 * A Terraform starting point for AWS. Every component whose catalog type
 * names an AWS resource, and that is meant for the cloud (no deploy target,
 * or AWS), gets that resource with the arguments the provider requires and
 * small default sizes. What a person must decide (images, networking,
 * credentials) is left as a comment, not invented.
 */

const byId = (a: { id: string }, b: { id: string }) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0);

/** A Terraform block name: letters, digits, underscores; never a leading digit. */
const tfName = (id: string) => {
  const s = id.toLowerCase().replace(/[^a-z0-9_]/g, '_');
  return /^[a-z_]/.test(s) ? s : `c_${s}`;
};
/** A cloud resource name: lowercase letters, digits and dashes. */
const slug = (s: string) =>
  s
    .replaceAll('ı', 'i')
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '') || 'sysarch';
const named = (n: ArchNode, max?: number) =>
  max ? `substr("\${var.project}-${slug(n.id)}", 0, ${max})` : `"\${var.project}-${slug(n.id)}"`;

const DB_ENGINES: Record<string, string> = { PostgreSQL: 'postgres', MySQL: 'mysql' };
const CACHE_ENGINES: Record<string, string> = {
  Redis: 'redis',
  Valkey: 'valkey',
  Memcached: 'memcached',
};

/** A resource block as lines, or the reason it was left out. */
function block(n: ArchNode, resource: string): string[] | string {
  const head = `resource "${resource}" "${tfName(n.id)}" {`;
  const label = `  # ${n.label}`;
  switch (resource) {
    case 'aws_ecs_service':
      return [
        head,
        label,
        `  name          = ${named(n)}`,
        '  cluster       = aws_ecs_cluster.main.id',
        '  launch_type   = "FARGATE"',
        '  desired_count = 1',
        '  # Build and push the image, then set task_definition and network_configuration.',
        '}',
      ];
    case 'aws_db_instance': {
      const engine = DB_ENGINES[String(n.props.engine)];
      if (!engine) return `${n.label}: no RDS engine for ${String(n.props.engine)}`;
      const storage = Math.max(20, Math.round(Number(n.props.storageGb) || 20));
      return [
        head,
        label,
        `  identifier                  = ${named(n)}`,
        `  engine                      = "${engine}"`,
        '  instance_class              = "db.t4g.micro"',
        `  allocated_storage           = ${storage}`,
        '  username                    = "app"',
        '  manage_master_user_password = true',
        '  skip_final_snapshot         = true',
        '}',
      ];
    }
    case 'aws_elasticache_cluster': {
      const engine = CACHE_ENGINES[String(n.props.engine)] ?? 'redis';
      return [
        head,
        label,
        `  cluster_id      = ${named(n, 40)}`,
        `  engine          = "${engine}"`,
        '  node_type       = "cache.t4g.micro"',
        '  num_cache_nodes = 1',
        '}',
      ];
    }
    case 'aws_sqs_queue':
      return [head, label, `  name = ${named(n)}`, '}'];
    case 'aws_lb':
      return [
        head,
        label,
        `  name               = ${named(n, 32)}`,
        '  load_balancer_type = "application"',
        '  internal           = false',
        '  subnets            = var.subnet_ids',
        '}',
      ];
    case 'aws_s3_bucket':
      return [head, label, `  bucket = ${named(n)}`, '}'];
    default:
      return `${n.label}: ${resource} is not generated yet`;
  }
}

/**
 * terraform/main.tf and variables.tf for the components that map to AWS.
 * Nothing when none does. ponytail: AWS only; Docker deployments are what
 * docker-compose.yml already covers.
 */
export function terraformFiles(doc: ArchDoc, catalog: Catalog): ExportFile[] {
  const blocks: string[][] = [];
  const skipped: string[] = [];
  for (const n of [...doc.nodes].sort(byId)) {
    const resource = catalog.get(n.type)?.exportHints.terraformResource?.aws;
    if (!resource || (n.deploy && n.deploy.target !== 'aws')) continue;
    const b = block(n, resource);
    if (typeof b === 'string') skipped.push(b);
    else blocks.push(b);
  }
  if (!blocks.length) return [];

  const main = [
    `# Generated by SysArch for "${doc.meta.name}". A starting point: review sizes,`,
    '# networking and credentials before applying.',
    'terraform {',
    '  required_providers {',
    '    aws = {',
    '      source  = "hashicorp/aws"',
    '      version = "~> 6.0"',
    '    }',
    '  }',
    '}',
    '',
    'provider "aws" {',
    '  region = var.region',
    '}',
    '',
  ];
  if (blocks.some((b) => b[0]!.startsWith('resource "aws_ecs_service"')))
    main.push('resource "aws_ecs_cluster" "main" {', '  name = var.project', '}', '');
  for (const b of blocks) main.push(...b, '');
  if (skipped.length) main.push('# Not generated:', ...skipped.map((s) => `#   ${s}`), '');

  const variables = [
    'variable "project" {',
    '  description = "Prefix for every resource name."',
    '  type        = string',
    `  default     = "${slug(doc.meta.name).slice(0, 20)}"`,
    '}',
    '',
    'variable "region" {',
    '  type    = string',
    '  default = "eu-central-1"',
    '}',
    '',
    'variable "subnet_ids" {',
    '  description = "Subnets for load balancers; an application load balancer needs two."',
    '  type        = list(string)',
    '  default     = []',
    '}',
    '',
  ];
  return [
    { path: 'terraform/main.tf', content: `${main.join('\n').trimEnd()}\n` },
    { path: 'terraform/variables.tf', content: variables.join('\n') },
  ];
}
